### ISSUE TITLE
🐛 Bug Report: Code of Conduct link broken in all issue templates

### ISSUE THREAD

**Issue by vj-codes** [appwrite/.github#10]
### 👟 Reproduction steps

Open the Code of Conduct link at the bottom

### 👍 Expected behavior

It should display the right window

### 👎 Actual Behavior

404 page

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by vj-codes** [comment]
Heyyo! Can I please be assigned to this? Thanks in advance:)

**Comment by stnguyen90** [comment]
@vj-codes assigned! Thanks for your interest!
