### ISSUE TITLE
How to get Posts created by users 

### ISSUE THREAD

**Issue by zionnite** [appwrite/.github#64]
### 💭 Description

Currently working with Appwrite, and I'm trying to simulate my app to Twitter App where users can follow and unfollow each other.

At the moment, users can create tweet, like tweet, comment on tweet, follow and unfollow each other but I want to be able to fetched tweet of users I'm following, I don't want to pull all the tweets to the user, only the person they are following.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Closing this issue in favor of https://github.com/appwrite/appwrite/discussions/6044
